"""Reusable application services for CLI, TUI, and future front ends.

This module keeps user-interface code out of the core workflow. Typer commands
can print Rich tables and exit with CLI codes; a TUI can call the same functions
and render state however it wants.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Protocol

from rich.console import Console

from . import pipeline
from .api import load_cohort
from .config import CohortSpec, LimitSpec, from_flags, load_yaml, read_projects_file
from .download import write_manifest_tsv
from .gdc import GDCClient


class SpecBuildError(ValueError):
    """Raised when user input is not enough to construct a cohort spec."""


class ProjectClient(Protocol):
    def list_projects(self, program: str = "TCGA") -> list[dict]: ...


@dataclass(frozen=True)
class CohortBuildOptions:
    """User-facing inputs that can produce a CohortSpec.

    These mirror the current CLI flags, but the shape is intentionally UI
    neutral so the future TUI can build specs without going through Typer.
    """

    config: Path | None = None
    name: str | None = None
    out: Path | None = None
    project: list[str] | None = None
    projects_file: Path | None = None
    data_type: list[str] | None = None
    data_category: list[str] | None = None
    data_format: list[str] | None = None
    experimental_strategy: list[str] | None = None
    workflow: list[str] | None = None
    sample_type: list[str] | None = None
    n_processes: int = 4
    limit_per_project: int | None = None


@dataclass(frozen=True)
class RecipeOutput:
    """Path-level result for a generated recipe artifact."""

    path: Path
    engine: str | None = None


@dataclass(frozen=True)
class FrequencyOutputs:
    """Outputs generated by the frequency recipe."""

    gene_frequency: Path
    variant_frequency: Path


@dataclass(frozen=True)
class ManifestOutput:
    """Result of writing a GDC manifest from a cohort preview."""

    path: Path
    n_files: int
    n_cases: int
    total_size: int


def build_cohort_spec(options: CohortBuildOptions) -> CohortSpec:
    """Construct a CohortSpec from YAML or direct filter inputs."""

    if options.config:
        spec = load_yaml(options.config, out_dir_override=options.out)
    else:
        projects: list[str] = list(options.project or [])
        if options.projects_file is not None:
            projects.extend(read_projects_file(options.projects_file))
        projects = list(dict.fromkeys(projects))

        if not projects:
            raise SpecBuildError(
                "Need either a YAML config, --project, or --projects-file. "
                "Try `tcga-pull projects` to list available projects."
            )

        cohort_name = options.name or default_cohort_name(projects, options.data_type)
        effective_out = (options.out or Path("./cohorts")).expanduser().resolve()
        spec = from_flags(
            name=cohort_name,
            out_dir=effective_out,
            project=projects,
            data_type=options.data_type,
            data_category=options.data_category,
            data_format=options.data_format,
            experimental_strategy=options.experimental_strategy,
            workflow=options.workflow,
            sample_type=options.sample_type,
            n_processes=options.n_processes,
        )

    if options.limit_per_project is not None:
        try:
            spec.limit = LimitSpec(per_project=options.limit_per_project)
        except ValueError as e:
            raise SpecBuildError(str(e)) from e
    return spec


def default_cohort_name(project: list[str], data_type: list[str] | None) -> str:
    if len(project) == 1:
        p = project[0].lower().replace("tcga-", "")
    else:
        p = f"multi_{len(project)}_projects"
    if data_type:
        dt = data_type[0].lower().replace(" ", "_")
        return f"{p}_{dt}"
    return p


def preview_cohort(
    spec: CohortSpec,
    *,
    client: GDCClient | None = None,
) -> pipeline.Preview:
    return pipeline.fetch_preview(spec, client=client)


def run_cohort(
    spec: CohortSpec,
    *,
    console: Console | None = None,
    client: GDCClient | None = None,
) -> Path:
    return pipeline.run(spec, console=console, client=client)


def write_manifest_from_preview(
    preview: pipeline.Preview,
    *,
    path: Path | None = None,
) -> ManifestOutput:
    manifest_path = path or preview.spec.cohort_dir / "manifest.tsv"
    n_files = write_manifest_tsv(preview.file_hits, manifest_path)
    return ManifestOutput(
        path=manifest_path,
        n_files=n_files,
        n_cases=preview.n_cases,
        total_size=preview.total_size,
    )


def write_manifest_for_spec(
    spec: CohortSpec,
    *,
    path: Path | None = None,
    client: GDCClient | None = None,
) -> ManifestOutput:
    preview = preview_cohort(spec, client=client)
    return write_manifest_from_preview(preview, path=path)


def list_projects(
    *,
    program: str = "TCGA",
    client: ProjectClient | None = None,
) -> list[dict]:
    rows = (client or GDCClient()).list_projects(program=program)
    return sorted(rows, key=lambda x: x.get("project_id") or "")


def resolve_variants_writer(engine: str):
    if engine == "polars":
        from .variants_polars import write_variants

        return write_variants
    if engine == "pandas":
        from .variants import write_variants

        return write_variants
    raise ValueError(f"unknown engine: {engine!r} (use 'polars' or 'pandas')")


def resolve_samples_writer(engine: str):
    if engine == "polars":
        from .samples_polars import write_samples

        return write_samples
    if engine == "pandas":
        from .samples import write_samples

        return write_samples
    raise ValueError(f"unknown engine: {engine!r} (use 'polars' or 'pandas')")


def write_variants_recipe(cohort_dir: Path, *, engine: str = "polars") -> RecipeOutput:
    writer = resolve_variants_writer(engine)
    return RecipeOutput(path=writer(cohort_dir), engine=engine)


def write_samples_recipe(cohort_dir: Path, *, engine: str = "polars") -> RecipeOutput:
    writer = resolve_samples_writer(engine)
    return RecipeOutput(path=writer(cohort_dir), engine=engine)


def write_frequency_recipe(cohort_dir: Path) -> FrequencyOutputs:
    from .frequency import write_gene_frequency, write_variant_frequency

    return FrequencyOutputs(
        gene_frequency=write_gene_frequency(cohort_dir),
        variant_frequency=write_variant_frequency(cohort_dir),
    )


def summarize_cohort(cohort_dir: Path) -> dict[str, int | str]:
    return load_cohort(cohort_dir).summary()
